// ─── lib/api.ts ───────────────────────────────────────────────────────────────
// READ-ONLY integration seam.
// Do NOT edit this file. Do NOT add fetch() calls in components.
// Swap mock ↔ real by changing lib/api-mode.ts only.
//
// This module delegates every call to whatever implementation lib/api-mode.ts
// selects. Signatures here are the contract; implementations live in
// lib/mock-api.ts (and eventually a real REST client).

import type {
  ApiResult,
  BuildResult,
  CompileRequest,
  CreateItemRequest,
  DeleteItemRequest,
  FileItem,
  FileTreeNode,
  Project,
  RenameItemRequest,
  VersionSnapshot,
  WriteFileRequest,
} from "@/lib/api-types"
import { impl } from "@/lib/api-mode"

// ─── Projects ─────────────────────────────────────────────────────────────────

/** Load the single active project (this app is single-project for now). */
export function fetchProject(): Promise<ApiResult<Project>> {
  return impl().fetchProject()
}

/** Rename the active project. */
export function renameProject(name: string): Promise<ApiResult<Project>> {
  return impl().renameProject(name)
}

// ─── File tree ────────────────────────────────────────────────────────────────

/** Return the full nested file tree for the active project. */
export function fetchFileTree(): Promise<ApiResult<FileTreeNode[]>> {
  return impl().fetchFileTree()
}

/** Return a flat list of all file items (for lookups). */
export function fetchFlatFiles(): Promise<ApiResult<FileItem[]>> {
  return impl().fetchFlatFiles()
}

// ─── Single file ──────────────────────────────────────────────────────────────

/** Read the content of a single file by ID. */
export function readFile(id: string): Promise<ApiResult<FileItem>> {
  return impl().readFile(id)
}

/** Write (overwrite) the content of a file. */
export function writeFile(req: WriteFileRequest): Promise<ApiResult<FileItem>> {
  return impl().writeFile(req)
}

// ─── File tree mutations ──────────────────────────────────────────────────────

/** Create a new file or folder. */
export function createItem(req: CreateItemRequest): Promise<ApiResult<FileItem>> {
  return impl().createItem(req)
}

/** Rename a file or folder. */
export function renameItem(req: RenameItemRequest): Promise<ApiResult<FileItem>> {
  return impl().renameItem(req)
}

/** Delete a file or folder (recursively for folders). */
export function deleteItem(req: DeleteItemRequest): Promise<ApiResult<{ deletedIds: string[] }>> {
  return impl().deleteItem(req)
}

// ─── Build / compile ─────────────────────────────────────────────────────────

/** Compile the project. Returns a build result with logs. */
export function compileLaTeX(req: CompileRequest): Promise<ApiResult<BuildResult>> {
  return impl().compileLaTeX(req)
}

/** Return the PDF URL for a given build ID. */
export function getPdfUrl(buildId: string): string {
  return impl().getPdfUrl(buildId)
}

// ─── Version history ──────────────────────────────────────────────────────────

/** List all snapshots for a file, newest first. */
export function listVersions(fileId: string): Promise<ApiResult<VersionSnapshot[]>> {
  return impl().listVersions(fileId)
}

/** Save a new snapshot for a file. */
export function saveVersion(
  fileId: string,
  content: string,
  label: string,
  isAutoSave: boolean
): Promise<ApiResult<VersionSnapshot>> {
  return impl().saveVersion(fileId, content, label, isAutoSave)
}

/** Update a snapshot's label or starred status. */
export function updateVersion(
  id: string,
  patch: Partial<Pick<VersionSnapshot, "label" | "isStarred">>
): Promise<ApiResult<VersionSnapshot>> {
  return impl().updateVersion(id, patch)
}

/** Delete a snapshot. */
export function deleteVersion(id: string): Promise<ApiResult<{ id: string }>> {
  return impl().deleteVersion(id)
}
